services:
  - type: web
    name: mes-fichiers-ekdata
    env: java
    region: frankfurt
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17